services:
  project_budget_db:
    image: postgres:17.4
    restart: always
    container_name: project_budget_db
    ports:
      - '5131:5432'
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - ./postgres:/var/lib/postgresql/data
  project_budget_backend:
    build: ./
    container_name: project_budget_db
    env_file:
      - ./.env
    ports:
      - '3010:3010'
    depends_on:
      - project_budget_db
    restart: always
