services:
  project_budget_db:
    image: postgres:17.4
    restart: always
    container_name: project_budget_db
    ports:
      - '${DB_PORT_EXPOSE}:${DB_PORT}'
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - ./postgres:/var/lib/postgresql/data
  project_budget_backend:
    build: ./
    image: project_budget:backend
    container_name: project_budget_api
    env_file:
      - ./.env
    ports:
      - '${PORT}:${PORT}'
    depends_on:
      - project_budget_db
    restart: always
